/* Lint rules, split by where the code actually runs.

   Every source file is an ES module now, so nearly all of this is the linter's
   default: it resolves imports itself, and a name that is not imported is an
   error rather than something the config has to declare. This file used to carry
   a globals map per game, generated by reading `globalThis.X =` out of the
   sources, because the game shipped as plain scripts sharing one page scope and
   a linter that assumed modules called every cross-file reference undefined.
   None of that is needed, and none of it is missed — `no-undef` is what caught
   a module using `Rules` without importing it during the move.

   Nothing here ships. eslint is a dev dependency; the built page still has no
   dependencies at all, which a test checks. */
import js from '@eslint/js';
import globals from 'globals';
import { readdirSync, existsSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));

/* What the pages put on `globalThis`, for the specs that drive one.

   A spec reaches these from inside `page.evaluate`, where they are genuinely
   globals of the page under test and nothing a linter could resolve. Read off
   the entry points rather than listed here, so the two cannot disagree: an entry
   point that stops publishing a name stops declaring it in the same commit, and
   the spec still naming it goes red rather than green.

   `Sound` and `Preview` are added by hand, because they are the two names no
   entry point's debug surface publishes: each is written by a deferred bundle
   and read by everything else, across a boundary an import cannot cross. */
const published = { Sound: 'writable', Preview: 'writable' };
for (const dir of readdirSync(join(root, 'src'), { withFileTypes: true })
  .filter(d => d.isDirectory() && existsSync(join(root, 'src', d.name, 'js')))
  .map(d => join('src', d.name, 'js'))
  .concat('src/js')){
  const entry = join(root, dir, 'main.js');
  if (!existsSync(entry)) continue;
  const surface = readFileSync(entry, 'utf8').match(/Object\.assign\(globalThis,\s*\{([^}]*)\}/);
  if (!surface) continue;
  for (const m of surface[1].matchAll(/([A-Za-z_$][\w$]*)\s*(?=[,}]|$)/g)) published[m[1]] = 'writable';
}

const shared = {
  /* A catch binding nobody reads is how this codebase says "the fallback is the
     point", so an unused one is not a mistake. An unused variable still is. */
  'no-unused-vars': ['error', { args: 'none', caughtErrors: 'none', varsIgnorePattern: '^_' }],
  'no-undef': 'error',
  /* an empty catch is how this codebase says "the fallback is the point", so it
     has to be deliberate rather than accidental */
  'no-empty': ['error', { allowEmptyCatch: true }],
  eqeqeq: ['error', 'always', { null: 'ignore' }],
  'no-var': 'error',
  'prefer-const': ['error', { destructuring: 'all' }],
  'no-implicit-globals': 'off',
  'no-console': 'off'
};

export default [
  /* `.claude/` holds tooling state, not project source, and `.claude/worktrees/`
     in particular holds whole checkouts of this repo. Without it here, having one
     open means linting a second copy of everything: the same files reported twice
     and, because a worktree carries a built `dist/` that the top-level ignore no
     longer matches at that depth, several hundred errors in generated code. Lint
     stops being runnable at all while a worktree exists. */
  { ignores: ['dist/**', 'node_modules/**', 'test-results/**', 'playwright-report/**', '.claude/**'] },

  /* first, so everything below can override it. Last, it silently puts back the
     rules the per-directory blocks turn off. */
  js.configs.recommended,

  /* Every game, as ES modules.

     One block, where there was a block per game. They were separate so that a
     reference from one game to another was a lint error rather than something
     that happened to work because both were in scope, and each carried a globals
     map naming what that game published.

     None of that is the linter's job now. Nothing is in scope that was not
     imported, so reaching into another game is a resolution error at build time
     rather than a rule somebody keeps writing down.

     Three declared globals, and all three are the same situation: a name that
     arrives over the network after the page has opened, which no import can
     express. `Sound` is the sound, handed from the stub to the real module once
     it lands. `BubbleApp` is the other game and `Preview` is the card shown
     before a replay, both fetched after first paint and both reached from the
     pour game behind a `typeof` guard. Importing any of them would put it in the
     critical bundle and undo the deferral. 49-audio.js says so at length. */
  {
    files: ['src/js/**/*.js', 'src/bubble/js/**/*.js', 'src/measure/js/**/*.js',
            'src/casks/js/**/*.js', 'src/lab/js/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.browser, Sound: 'writable', BubbleApp: 'writable', Preview: 'writable' }
    },
    rules: shared
  },

  /* the solver runs in a worker, and is written to survive being loaded as one */
  {
    files: ['src/worker/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: { ...globals.worker }
    },
    rules: { ...shared, 'no-var': 'off', 'prefer-const': 'off' }
  },

  /* The service worker. Source only: the copy in dist/ is this file with three
     constants stamped in, and dist/** is ignored above, so listing it here
     matched nothing and said the config covered a build output it never saw. */
  {
    files: ['src/sw.js'],
    languageOptions: { ecmaVersion: 2022, sourceType: 'script', globals: globals.serviceworker },
    rules: shared
  },

  /* tools and tests: real modules, running in node */
  {
    files: ['tools/**/*.mjs', 'tests/**/*.mjs', 'eslint.config.js', 'playwright.config.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: globals.node
    },
    rules: shared
  },

  /* the end to end specs drive a browser from node, so they see both */
  {
    files: ['tests/e2e/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.node, ...globals.browser, ...published }
    },
    rules: shared
  }
];
