/* No shipped level may brick more than its chapter can rescue.

   A board bricks when ordinary play reaches a state with no useful pour left.
   Every board is solvable when it is dealt, so this is the player painting
   themselves into a corner rather than an impossible deal, and it is a separate
   axis from the difficulty the ordering sorts on: two twelve-color boards
   measured at 9.92 and 9.93 slips brick at 42% and 92%. Nothing selected for it
   until this file existed, so it drifted free, and the levels it drifted worst
   on were the ones where the player has nothing to spend against it.

   What the ceiling is and why it steps where it does is tools/brick-core.mjs.

   Two checks, because the committed measurement and the live one can each go
   wrong on their own. The table can go stale against a regenerated order, and
   the order can be regenerated against a ceiling somebody moved. */
import { describe, it, assert, equal, loadPure, read } from './helpers.mjs';
import { measure, ceilingFor } from '../tools/brick-core.mjs';

const { Levels, Chapters, CONFIG } = loadPure();
const curve = JSON.parse(read('docs/difficulty.json')).levels;

/* Where the vessel is granted, read off the chapter list rather than written
   down here. Moving the grant moves the ceiling, and this test moves with it. */
const vesselLevel = (() => {
  for (let i = 0; i < Chapters.count; i++){
    const c = Chapters.at(i);
    if (c && c.grant === 'vessel') return i * CONFIG.sectionSize + 1;
  }
  return Infinity;
})();

const pct = n => `${(n * 100).toFixed(1)}%`;

describe('bricking', () => {
  it('grants the vessel before the ceiling relaxes', () => {
    /* The ceiling steps up because the vessel arrives, so a chapter list that no
       longer grants it would leave the relaxed ceiling standing on nothing. */
    assert(Number.isFinite(vesselLevel), 'no chapter grants the vessel, so the brick ceiling has no basis');
    assert(ceilingFor(vesselLevel - 1, vesselLevel) < ceilingFor(vesselLevel, vesselLevel),
      'the ceiling does not actually relax where the vessel is granted');
  });

  it('measures the same board twice the same way', () => {
    /* Seeded, because the ceiling below is asserted against these numbers and a
       measurement that wandered would make this suite flap. */
    const tubes = Levels.make(19);
    equal(measure(tubes, 19, { runs: 40 }), measure(tubes, 19, { runs: 40 }),
      'the same board measured differently twice');
  });

  it('keeps every level under the ceiling its chapter can afford', () => {
    const over = curve
      .filter(r => typeof r.brick === 'number')
      .filter(r => r.brick > ceilingFor(r.level, vesselLevel))
      .map(r => `level ${r.level} bricks ${pct(r.brick)} against a ceiling of ${pct(ceilingFor(r.level, vesselLevel))}`);
    equal(over, [], `${over.length} levels are over their brick ceiling`);
  });

  it('has a committed measurement for every level it deals', () => {
    const missing = curve.filter(r => typeof r.brick !== 'number').map(r => r.level);
    equal(missing, [], 'levels in the curve with no brick measurement');
  });

  it('still bricks as often as the committed table says', () => {
    /* The table is generated by `npm run order` and pinned above, which catches a
       ceiling somebody moved but not a table that stopped describing the boards.
       Re-measuring all 120 costs minutes, so this re-measures a spread of them
       and fails if the committed number is not what the board actually does. */
    const sample = curve.filter(r => r.level % 17 === 0 || r.level <= 2);
    assert(sample.length >= 6, 'the sample is too small to catch a stale table');
    const wrong = [];
    for (const r of sample){
      if (Levels.isBubble(r.level)) continue;
      const got = measure(Levels.make(r.level), r.seed).brick;
      /* Generated at 200 runs and re-measured at 200 runs off the same seed, so
         this is an equality check with room only for the rounding the table does. */
      if (Math.abs(got - r.brick) > 0.005)
        wrong.push(`level ${r.level}: table says ${pct(r.brick)}, board does ${pct(got)}`);
    }
    equal(wrong, [], 'the committed brick table no longer describes the boards');
  });
});
