import { run } from './helpers.mjs';
import './rules.test.mjs';
import './solver.test.mjs';
import './levels.test.mjs';
import './pars.test.mjs';
import './progress.test.mjs';
import './panel.test.mjs';
import './playthrough.test.mjs';
import './economy.test.mjs';
import './palette.test.mjs';
import './map.test.mjs';
import './queue.test.mjs';
import './build.test.mjs';
await run();
