/* Generated by `npm run casks:field`. Do not edit by hand.

   The floor of every level, four characters per cask — axis, length, the row or
   column it is pinned to, and where it starts. CasksLevels.parse reads it and
   CasksLevels.encode wrote it, so the format is defined once and the tool cannot
   spell it differently from the page.

   These are not seeds. A random scattering of casks is overwhelmingly likely to
   be trivial and finding out costs a sweep of the layout's whole reachable
   component, so the boards themselves are measured offline and shipped. The
   opposite of what src/measure/js does, and the reason is cost rather than
   principle; the note at the top of 30-levels.js sets it out.

   Every board here is the state PROVABLY FURTHEST from the door in its layout's
   reachable component, which is the hardest start that layout can offer.
   Regenerating this moves every level, so 35-pars.js has to be regenerated with
   it. The tool writes both, in one pass, from one measurement, for that reason. */
globalThis.CasksBoards = Object.freeze({1:'h220h244h233h240h202h250h252h230h211',2:'h220h341h330v200v231h250',3:'h220h201h211v213h333v350',4:'h220v242h202v203h210h342h313h331v252h353',5:'h220v224h253h202v213v303v342h311v252v254v240',6:'h220h331v251h302v210h244h353h250h340v241',7:'h220h254h201h231h311h233v350v203v340',8:'h220h251h211h254v222v253h342v213h303h201v200',9:'h221v242v220v251v201h303v244v232h252v254h231',10:'h220h331h213h302h341v221v352h353v210v250',11:'h221v224h244h211h250v340v300v234v252',12:'h220h203v214v350v224h201h311v200v234v342v232h254',13:'h220h234v321v340h201v331v251v200',14:'h220h244h300v224h233v340h253v250v222h211',15:'h222v211v220h213h231h203v351v233h353h244h200',16:'h220v352v320h342v230v242v200h214h204v313',17:'h220v203v351h241h310h250h233v340v234v222',18:'h221v223h200v340v220v230h253v201h243v351',19:'h221h330v352v230h342h254h351v201h204v242v220h240',20:'h220v350v232v203v221h300v230v342h352h242v240'});
