/* Generated by `npm run casks:field`. Do not edit by hand.

   The exact minimum for every level, from a multi-source breadth first sweep
   over the whole reachable component of that level's layout. Boards are a
   shipped table rather than a seed, so par is a fixed property of a level and is
   never recomputed in the page: a slow phone shows the same number as a fast
   laptop, and the number both show is the one the levels were chosen against.

   `last` travels in the same object rather than as a second global, because a
   par table and the level it ends at are one fact and publishing them separately
   invites them to disagree. A board with no par here is not an unmeasured board,
   it is these two tables having come apart — and 45-score.js gives it NO STARS
   rather than full marks. That is the opposite of what the pour game's
   Rules.rate() does with a missing par, and the inversion is deliberate: see
   45-score.js, which explains which way round it is and why. */
globalThis.CasksPars = Object.freeze({ last: 20, par: Object.freeze({1:1,2:2,3:3,4:4,5:5,6:6,7:7,8:8,9:9,10:10,11:11,12:12,13:13,14:14,15:15,16:16,17:17,18:18,19:19,20:20}) });
