/* Generated by `npm run pars`. Do not edit by hand.

   Par for every level, precomputed with an offline search budget. Levels are
   deterministic in the level number, so these values are stable: the same
   puzzle, and the same true minimum, for everyone.

   LAST_LEVEL is where the graded game ends, and progression stops there. Without
   a known par a run cannot be scored: rate() has no bar to measure against, so it
   awards full marks, which past the end of the table would mean a level that can
   neither be failed nor played badly, paying out forever. Solving in the browser
   is the fallback for a level whose par is missing, not a license to ship one. */
export const PARS = Object.freeze({1:10,2:11,3:15,4:18,5:15,6:17,7:25,8:21,9:25,10:22,11:31,12:32,13:28,14:29,15:39,16:35,17:36,18:40,19:40,20:38,21:39,22:34,23:35,24:38,25:40,26:38,27:35,28:37,29:37,30:36,31:37,32:36,33:35,34:33,35:37,36:37,37:39,38:39,39:38,40:37,41:37,42:35,43:37,44:37,45:40,46:36,47:37,48:39,49:41,50:39,51:37,52:38,53:37,54:36,55:35,56:40,57:40,58:33,59:40,60:40,61:38,62:37,63:40,64:37,65:38,66:40,67:39,68:39,69:38,70:38,71:38,72:35,73:37,74:37,75:36,76:34,77:39,78:39,79:37,80:40,81:38,82:39,83:39,84:40,85:38,86:39,87:38,88:36,89:41,90:37,91:35,92:36,93:40,94:41,95:39,96:37,97:37,98:37,99:37,100:35,101:39,102:36,103:42,104:37,105:37,106:39,107:41,108:39,109:38,110:35,111:34,112:40,113:38,114:40,115:39,116:38,117:39,118:40,119:37,120:38});
export const LAST_LEVEL = 120;
