/* Generated by `npm run casks:field`. Do not edit by hand.

   The exact minimum for every level, from a multi-source breadth first sweep
   over the whole reachable component of that level's layout. Boards are a
   shipped table rather than a seed, so par is a fixed property of a level and is
   never recomputed in the page: a slow phone shows the same number as a fast
   laptop, and the number both show is the one the levels were chosen against.

   `last` travels in the same object rather than as a second global, because a
   par table and the level it ends at are one fact and publishing them separately
   invites them to disagree. A board with no par here is not an unmeasured board,
   it is these two tables having come apart — and 45-score.js gives it NO STARS
   rather than full marks. That is the opposite of what the pour game's
   Rules.rate() does with a missing par, and the inversion is deliberate: see
   45-score.js, which explains which way round it is and why. */
export const CasksPars = Object.freeze({ last: 58, par: Object.freeze({1:4,2:4,3:5,4:5,5:6,6:6,7:7,8:7,9:8,10:8,11:9,12:9,13:10,14:10,15:11,16:11,17:12,18:12,19:13,20:13,21:14,22:14,23:15,24:15,25:16,26:16,27:17,28:17,29:18,30:18,31:19,32:19,33:20,34:20,35:21,36:21,37:22,38:22,39:23,40:23,41:24,42:24,43:25,44:25,45:26,46:26,47:27,48:27,49:28,50:28,51:30,52:30,53:31,54:31,55:32,56:32,57:33,58:42}) });
