/* Generated by `npm run measure:field`. Do not edit by hand.

   What each level deals, as [vessels, seed], which MeasureLevels.fromSeed turns
   back into a bench and a target. Chosen on par AND on how much of a decision
   each step of that par is: sorting the field on length alone fills the first
   half of the game with two-pour boards that have one line through them. See
   tools/measure-field.mjs.

   Regenerating this moves every level, so 35-pars.js has to be regenerated with
   it. The tool writes both, in one pass, from one measurement, for that reason. */
globalThis.MeasureOrder = Object.freeze({1:[4,2133],2:[4,6215],3:[4,10124],4:[4,10725],5:[4,141],6:[4,2122],7:[4,882],8:[4,6640],9:[4,10955],10:[4,2693],11:[4,2589],12:[4,4918],13:[4,3982],14:[4,10432],15:[4,14070],16:[4,3506],17:[4,3132],18:[4,15265],19:[4,17780],20:[4,13859],21:[4,9625],22:[4,2605],23:[4,13378],24:[4,2519],25:[4,1855],26:[4,17465],27:[4,4509],28:[4,16645],29:[4,14090],30:[4,11960],31:[4,16056],32:[4,10932],33:[4,6617],34:[4,17678],35:[4,2223],36:[4,12393],37:[4,16563],38:[4,2958],39:[4,10862],40:[4,5278]});
