#!/usr/bin/env node
/* Build: inline every source file into dist/index.html, copy assets, emit the
   manifest and a service worker whose cache name changes with the content. */
import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync, cpSync, statSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');
const read = p => readFileSync(join(root, p), 'utf8');
const sorted = dir => readdirSync(join(root, dir)).filter(f => !f.startsWith('.')).sort();

const css = sorted('src/css').map(f => read(`src/css/${f}`)).join('\n');
const js  = sorted('src/js').map(f => `\n/* ---- ${f} ---- */\n${read(`src/js/${f}`)}`).join('\n');
const solver = read('src/worker/solver.js');

const fontFace = (fraunces, grotesk) => `<style>
@font-face{font-family:'Fraunces';font-style:normal;font-weight:600 900;font-display:swap;src:url(${fraunces}) format('woff2')}
@font-face{font-family:'Space Grotesk';font-style:normal;font-weight:400 700;font-display:swap;src:url(${grotesk}) format('woff2')}
</style>`;

const pwaHead = `<link rel="manifest" href="./manifest.webmanifest">
<link rel="icon" href="./icons/favicon-32.png" sizes="32x32">
<link rel="apple-touch-icon" href="./icons/apple-touch-icon.png">`;

function compose({ fonts, head }){
  return read('src/index.html')
    .replace('<!--PWAHEAD-->', head)
    .replace('<!--FONTS-->', fonts)
    .replace('<!--CSS-->', () => css)
    .replace('<!--SOLVER-->', () => solver)
    .replace('<!--JS-->', () => js);
}

rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
cpSync(join(root, 'assets/fonts'), join(dist, 'fonts'), { recursive: true });
cpSync(join(root, 'assets/icons'), join(dist, 'icons'), { recursive: true });

/* 1. the installable app, fonts as separate cacheable files */
const app = compose({ fonts: fontFace('./fonts/fraunces.woff2', './fonts/spacegrotesk.woff2'), head: pwaHead });
writeFileSync(join(dist, 'index.html'), app);

/* 2. one portable file, fonts inlined, opens straight off disk */
const b64 = p => 'data:font/woff2;base64,' + readFileSync(join(root, p)).toString('base64');
writeFileSync(join(dist, 'decanter-standalone.html'),
  compose({ fonts: fontFace(b64('assets/fonts/fraunces.woff2'), b64('assets/fonts/spacegrotesk.woff2')), head: '' }));

writeFileSync(join(dist, 'manifest.webmanifest'), JSON.stringify({
  id: '/decanter/',
  name: 'Decanter',
  short_name: 'Decanter',
  description: 'A water sorting puzzle. Pour until every bottle holds one color.',
  start_url: './',
  scope: './',
  display: 'standalone',
  display_override: ['standalone', 'fullscreen', 'minimal-ui'],
  orientation: 'portrait',
  background_color: '#0b0426',
  theme_color: '#150836',
  categories: ['games', 'puzzle'],
  icons: [
    { src: './icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: './icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: './icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' }
  ]
}, null, 2) + '\n');

/* precache list is derived from what actually landed in dist */
const walk = (dir, base = '') => readdirSync(dir).flatMap(f => {
  const full = join(dir, f);
  return statSync(full).isDirectory() ? walk(full, `${base}${f}/`) : [`${base}${f}`];
});
const assets = walk(dist)
  .filter(f => f !== 'sw.js' && f !== 'decanter-standalone.html')
  .map(f => `./${f}`);
assets.unshift('./');

const version = 'decanter-' + createHash('sha256').update(app).digest('hex').slice(0, 10);
writeFileSync(join(dist, 'sw.js'), `/* generated by tools/build.mjs, do not edit */
const VERSION = '${version}';
const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener('install', e => {
  e.waitUntil(caches.open(VERSION).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== VERSION).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  if (req.mode === 'navigate'){
    e.respondWith(fetch(req).catch(() => caches.match('./index.html', { ignoreSearch: true })));
    return;
  }
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then(hit => hit || fetch(req).then(res => {
      if (res && res.ok && new URL(req.url).origin === location.origin){
        const copy = res.clone();
        caches.open(VERSION).then(c => c.put(req, copy));
      }
      return res;
    }).catch(() => hit))
  );
});
`);

const kb = n => (n / 1024).toFixed(1) + 'kb';
console.log('built dist/');
console.log('  index.html               ', kb(app.length));
console.log('  decanter-standalone.html ', kb(readFileSync(join(dist, 'decanter-standalone.html')).length));
console.log('  sw.js                    ', version, `(${assets.length} precached)`);
