/* Precomputes par for every level and writes src/js/pure/35-pars.js.

   Levels are deterministic in the level number, so par is a fixed property of
   the level, not something worth rediscovering in the browser on every visit.
   Solving here, with a budget no page load could afford, means the shipped app
   always shows a true minimum instead of falling back to an estimate.

   Run `npm run pars` after changing the generator, the capacity, or the solver.
   The generated file is committed. */
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadPure, loadSolver } from '../tests/helpers.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const LEVELS = Number(process.argv[2] || 120);

/* far past what a page load would tolerate, so every level resolves exactly */
const BUDGET = { nodeCap: 20000000, msCap: 120000 };

const ctx = loadPure();
const solver = loadSolver();

const pars = {};
const slow = [];
let worst = 0;

for (let level = 1; level <= LEVELS; level++) {
  const { colors } = ctx.Levels.shape(level);
  const tubes = ctx.Levels.make(level);
  if (!tubes) throw new Error(`level ${level}: generator produced no board`);

  const started = Date.now();
  const got = solver.solve(tubes, colors, BUDGET);
  const ms = Date.now() - started;
  worst = Math.max(worst, ms);

  if (!got.exact || !Number.isInteger(got.par)) {
    throw new Error(`level ${level}: no exact par (got ${got.par}, exact ${got.exact})`);
  }
  pars[level] = got.par;
  if (ms > 1000) slow.push(`${level} (${ms}ms)`);
  if (level % 10 === 0) process.stdout.write(`  solved ${level}/${LEVELS}\n`);
}

const graded = Object.keys(pars).map(Number).sort((a, b) => a - b);
const entries = graded.map(k => `${k}:${pars[k]}`).join(',');
const out = `/* Generated by \`npm run pars\`. Do not edit by hand.

   Par for every level, precomputed with an offline search budget. Levels are
   deterministic in the level number, so these values are stable: the same
   puzzle, and the same true minimum, for everyone.

   LAST_LEVEL is where the graded game ends, and progression stops there. Without
   a known par a run cannot be scored: rate() has no bar to measure against, so it
   awards full marks, which past the end of the table would mean a level that can
   neither be failed nor played badly, paying out forever. Solving in the browser
   is the fallback for a level whose par is missing, not a licence to ship one. */
globalThis.PARS = Object.freeze({${entries}});
globalThis.LAST_LEVEL = ${graded[graded.length - 1]};
`;

writeFileSync(join(root, 'src/js/pure/35-pars.js'), out);

console.log(`\nwrote src/js/pure/35-pars.js with ${LEVELS} levels`);
console.log(`slowest solve: ${worst}ms`);
if (slow.length) console.log(`over 1s: ${slow.join(', ')}`);
